site_name: "Rafał Zarajczyk"
site_url: "http://rzarajczyk.github.io"
theme:
  name: material
  logo: "https://zarajczyk.pl/rafal/favicon.ico"
  favicon: "https://zarajczyk.pl/rafal/favicon.ico"
  features:
    - content.code.copy
    - content.code.annotate
extra_css:
  - extra.css
extra_javascript:
  - extra.js
nav:
  - index.md
  - 'General':
    - 'general-jvm-conferences.md'
    - 'general-search-conferences.md'
    - 'general-github.md'
    - 'general-interesting-online-tools.md'
    - 'general-biased-random.md'
  - 'MacOS':
    - 'macos-setup.md'
    - 'macos-memory-statistics.md'
    - 'macos-docker-without-docker-desktop.md'
    - 'macos-running-amd64-images-on-apple-m1.md'
  - 'Ubuntu':
    - 'ubuntu-setup.md'
    - 'ubuntu-logitech-mx-keys.md'
    - 'ubuntu-logitech-mx-vertical.md'
extra:
  analytics:
    provider: google
    property: UA-18093684-8
  consent:
    title: We're collecting traffic stats in 🍪 cookies
    description: >-
      <p>We're using Google Analytics for collecting traffic statistics.<br>
      If you want to know the details, check out this link: <a href="http://www.google.com/policies/technologies/types/" target="_blank">Cookies used by Google</a></p>
      <p>We're not using any other cookies.</p>
      <p>You can turn off Google Analytics cookie by disabling cookies in your browser:
      <a href="https://support.google.com/accounts/answer/61416?hl=en&co=GENIE.Platform%3DDesktop" target="_blank">How to disable cookies</a></p>
copyright: Copyright &copy; 2020 - 2023 Rafał Zarajczyk - <a href="/no-warranties">no warranties given! - license</a>
plugins:
  - search
  - glightbox:
      draggable: false
markdown_extensions:
  - admonition
  - tables
  - attr_list
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: 'docs/'
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg